### ISSUE TITLE
Atlass.Framework.Web/Controllers/Cms/ContentController.cs 没有找到GenerateContentAppService的定义

### ISSUE THREAD

**Issue by WeiweiCai** [yushuo1990/EasyCMS#5]
在Atlass.Framework.Web/Controllers/Cms/ContentController.cs里，GenerateContentAppService显示没有找到。请问这个类的定义应该在哪里？
![image](https://user-images.githubusercontent.com/15260217/88017991-5feb3780-cb59-11ea-8501-c2184a063bf8.png)

**Comment by seamusic** [comment]
同样的问题咯。

**Comment by jasonyush** [comment]
不好意思，前段时间自考，改动后没有及时更新，类名做了调整，GenerateContentAppService改为GenerateAppService或者拉取最新代码，已经更新
