### ISSUE TITLE
研究项目时遇到的问题

### ISSUE THREAD

**Issue by iisp** [yushuo1990/EasyCMS#7]
数据库SQL Service
1 生成出来的数据表，字段顺序不对
2 build() 产生数据表的时候，提示实体中 int 字段不需要带长度
3 管理端登录成功的时候，菜单不全。（数据库中一共就只有4长表）

**Comment by jasonyush** [comment]
你好 目前只有mysql和postgresql脚本，

**Comment by jasonyush** [comment]
已经添加了SqlServer的支持，请拉取最新代码，包含sqlserver脚本了
