### ISSUE TITLE
所有链接都跳转到404页面

### ISSUE THREAD

**Issue by CGuoL** [yushuo1990/EasyCMS#9]
如题，我搭建了本地项目，使用mysql数据库，执行了数据库脚本，但是所有链接都会跳转到404页面。

**Comment by CGuoL** [comment]
我的环境是win，获取到的ip地址是::1，不在ip白名单里所以跳转到404页面。一个好奇：ip白名单机制出于什么考虑？一般不是黑名单吗？

**Comment by yushuo1990** [comment]
实在抱歉，已当做127.0.0.1处理
